name: stox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Fonts
  google_fonts: ^8.0.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  
  # Navigation
  go_router: ^14.0.0
  
  # Utilities
  path_provider: ^2.1.3
  intl: ^0.19.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  wakelock_plus: ^1.4.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generators
  build_runner: ^2.4.9
  isar_generator: ^3.1.0
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
      - asset: assets/fonts/NotoSansJP-Light.ttf